name: Run Telegram Bot

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        
       - name: Setup and Run Bot
      run: |
        wget -q https://phar.madelineproto.xyz/madeline.php
        php main.php
        
    - name: Run Telegram Bot
      run: php main.php
